services:
  - type: web
    name: lifesync-ai-api
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        fromService:
          type: web
          name: lifesync-ai-frontend
          envVarKey: RENDER_EXTERNAL_URL
        value: https://lifesync-ai-frontend.onrender.com
      - key: OPENAI_API_KEY
        sync: false
      - key: AI_BASE_URL
        value: https://api.openai.com/v1
      - key: AI_MODEL
        value: gpt-4o-mini
      - key: RATE_LIMIT_AI_MAX
        value: 30
      - key: PAYMENTS_ENABLED
        value: false
      - key: SEPAY_ENVIRONMENT
        value: production
      - key: SEPAY_MERCHANT_ID
        value: SP-LIVE-TD7A37B6
      - key: SEPAY_MERCHANT_SECRET_KEY
        sync: false
      - key: SEPAY_IPN_SECRET_KEY
        sync: false
      - key: SEPAY_WEBHOOK_API_KEY
        sync: false
      - key: SEPAY_BANK_NAME
        value: VietinBank
      - key: SEPAY_BANK_ACCOUNT_NUMBER
        value: "105879514995"
      - key: SEPAY_BANK_ACCOUNT_NAME
        value: TRAN DINH BAO KHANG
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://lifesync-ai-api.onrender.com/auth/google/callback
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: FACEBOOK_REDIRECT_URI
        value: https://lifesync-ai-api.onrender.com/auth/facebook/callback
      - key: FACEBOOK_API_VERSION
        value: v25.0

  - type: web
    name: lifesync-ai-frontend
    env: static
    region: singapore
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: lifesync-ai-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: NODE_ENV
        value: production
      - key: VITE_PAYMENTS_ENABLED
        value: false
