import { Outlet, NavLink, Link, useNavigate } from 'react-router-dom';
import { Activity, Users, Database, Settings, ChevronDown, Menu, X, PanelLeftClose, PanelLeftOpen, LogOut, Search, Layers, ArrowUpRight } from 'lucide-react';
import { useState, useEffect } from 'react';
import { useAuthStore } from '../../store/auth.store';
import '../../admin-theme.css';
import '../../pages/admin/admin-dashboard.css';
const groups=[{label:'Tổng quan',icon:Activity,links:[{to:'/admin',label:'Bảng điều khiển',end:true},{to:'/admin/activity',label:'Nhật ký hoạt động'}]},{label:'Người dùng',icon:Users,links:[{to:'/admin/users',label:'Danh sách tài khoản'}]},{label:'Nội dung & giao diện',icon:Layers,links:[{to:'/admin/landing',label:'Biên tập landing page'}]},{label:'Hệ thống',icon:Database,links:[{to:'/admin/database',label:'Quản lý dữ liệu'},{to:'/admin/settings',label:'Cấu hình hệ thống'}]}];
export function AdminLayout(){
 const {user,logout}=useAuthStore();const navigate=useNavigate();
 const [mobile,setMobile]=useState(false);const [collapsed,setCollapsed]=useState(false);const [search,setSearch]=useState('');const [open,setOpen]=useState<Record<string,boolean>>({'Tổng quan':true,'Người dùng':true,'Hệ thống':true,'Nội dung & giao diện':true});
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMobile(false);setSearch('');}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
 const results=groups.flatMap(g=>g.links).filter(l=>l.label.toLowerCase().includes(search.toLowerCase()));
 return <div className={`admin-theme px-shell ${collapsed?'px-collapsed':''}`}>
 <header className="px-topbar"><Link to="/admin" className="px-brand"><Layers size={30}/><span>LifeSync<span> AI</span></span></Link><button className="px-mobile-button" aria-label="Mở điều hướng" aria-expanded={mobile} onClick={()=>setMobile(true)}><Menu size={21}/></button><div className="px-search-wrap"><label className="px-global-search"><Search size={18}/><input aria-label="Tìm trang quản trị" placeholder="Tìm trang quản trị..." value={search} onChange={e=>setSearch(e.target.value)}/></label>{search&&<div className="px-search-results">{results.length?results.map(r=><Link key={r.to} to={r.to} onClick={()=>setSearch('')}>{r.label}<ArrowUpRight size={14}/></Link>):<p>Không tìm thấy trang phù hợp.</p>}</div>}</div><div className="px-top-tools"><Link to="/admin/settings" aria-label="Cấu hình hệ thống"><Settings size={20}/></Link><Link to="/app" className="px-app-link">Mở ứng dụng <ArrowUpRight size={15}/></Link><span className="px-profile" title={user?.name}>{user?.name?.charAt(0)||'A'}</span></div></header>
 {mobile&&<button className="px-overlay" aria-label="Đóng điều hướng" onClick={()=>setMobile(false)}/>}
 <aside className={`px-sidebar ${mobile?'open':''}`}><button className="px-mobile-close" aria-label="Đóng điều hướng" onClick={()=>setMobile(false)}><X size={20}/></button><nav aria-label="Điều hướng quản trị"><p className="px-nav-caption">KHÔNG GIAN LÀM VIỆC</p>{groups.map(({label,icon:Icon,links})=><div className="px-nav-group" key={label}><button title={label} aria-expanded={!!open[label]} onClick={()=>{if(collapsed)setCollapsed(false);setOpen(o=>({...o,[label]:!o[label]}));}}><ChevronDown size={12} className={open[label]?'':'closed'}/><Icon size={18}/><span>{label}</span></button>{open[label]&&<div className="px-subnav">{links.map(link=><NavLink key={link.to} to={link.to} end={'end' in link?link.end:false} onClick={()=>setMobile(false)}>{link.label}</NavLink>)}</div>}</div>)}<p className="px-nav-caption">LIFESYNC AI</p><Link className="px-return" to="/app"><ArrowUpRight size={18}/><span>Không gian cá nhân</span></Link></nav><div className="px-sidebar-footer"><button onClick={()=>setCollapsed(v=>!v)} aria-label={collapsed?'Mở rộng sidebar':'Thu gọn sidebar'} className="px-collapse">{collapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}<span>Thu gọn menu</span></button><button className="px-signout" onClick={async()=>{await logout();navigate('/admin/login',{replace:true});}} title="Đăng xuất"><LogOut size={17}/><span>Đăng xuất</span></button></div></aside>
 <main className="px-main"><Outlet/></main></div>;
}
