import { useState } from 'react';
import { Check, Clipboard, Download, FileCheck2, RefreshCw, ShieldCheck, TriangleAlert, Upload } from 'lucide-react';
import { Button } from '../../components/ui';
import { showToast } from '../../components/ui/toast';
import api from '../../services/api';
import '../../admin-theme.css';

interface BackupGuideResponse { status: string; message: string; backupCommand: string; restoreCommand: string; safety?: string[]; timestamp: string; }
const fallback: BackupGuideResponse = { status: 'manual_required', message: 'API chỉ kiểm tra runbook. Chạy lệnh trên máy triển khai với biến môi trường bảo mật.', backupCommand: 'mysqldump --defaults-extra-file="$MYSQL_CNF" "$MYSQL_DATABASE" > "backup-$(date +%Y%m%d-%H%M%S).sql"', restoreCommand: 'mysql --defaults-extra-file="$MYSQL_CNF" "$MYSQL_DATABASE" < "./backup.sql"', safety: ['Không ghi mật khẩu trực tiếp vào lệnh hoặc log.', 'Kiểm tra checksum và thử phục hồi trên staging trước production.'], timestamp: '' };

function CopyButton({ value }: { value: string }) { const [copied, setCopied] = useState(false); const copy = async () => { await navigator.clipboard.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }; return <button type="button" className="admin-copy-button" onClick={() => void copy()} aria-label="Sao chép lệnh">{copied ? <Check size={15} /> : <Clipboard size={15} />}{copied ? 'Đã sao chép' : 'Sao chép'}</button>; }

export function DatabaseManagement() {
    const [checking, setChecking] = useState(false); const [guide, setGuide] = useState<BackupGuideResponse | null>(null); const [restoreArmed, setRestoreArmed] = useState(false); const current = guide ?? fallback;
    const validate = async () => { setChecking(true); try { const response = await api.post('/admin/backup'); setGuide(response.data.data); showToast.success('Runbook đã sẵn sàng', 'Không có thao tác ghi dữ liệu nào được thực hiện.'); } catch { showToast.error('Không thể tải runbook', 'Kiểm tra quyền quản trị và thử lại.'); } finally { setChecking(false); } };
    return <div className="admin-theme admin-container p-6 md:p-8">
        <div className="admin-page-head"><div><p className="admin-kicker">HỆ THỐNG / DỮ LIỆU</p><h1 className="admin-title">Quản lý dữ liệu</h1><p className="admin-title-sub">Backup có kiểm soát, phục hồi có xác nhận và checklist triển khai.</p></div><Button size="lg" onClick={() => void validate()} disabled={checking} className="admin-btn admin-btn-primary"><RefreshCw size={17} className={checking ? 'animate-spin' : ''} />{checking ? 'Đang kiểm tra...' : 'Kiểm tra runbook'}</Button></div>
        <div className="admin-ops-banner"><div className="admin-ops-icon"><ShieldCheck size={21} /></div><div><strong>Chế độ vận hành an toàn</strong><p>Trang này không tự ý tải hoặc phục hồi cơ sở dữ liệu. Mọi lệnh đều chạy ngoài API bằng thông tin kết nối đã được quản lý trên máy triển khai.</p></div><span className="admin-status-pill">Thủ công</span></div>
        <section className="admin-backup-grid"><article className="admin-glass-card admin-command-card"><div className="admin-card-heading"><span className="admin-soft-icon green"><Download size={18} /></span><div><h2>Tạo bản backup</h2><p>Xuất snapshot trước deploy hoặc migration.</p></div></div><pre><code>{current.backupCommand}</code></pre><CopyButton value={current.backupCommand} /><p className="admin-help">Dùng <code>$MYSQL_CNF</code> chứa credential ngoài repository.</p></article><article className="admin-glass-card admin-command-card"><div className="admin-card-heading"><span className="admin-soft-icon amber"><Upload size={18} /></span><div><h2>Phục hồi dữ liệu</h2><p>Chỉ thực hiện sau khi đã xác nhận đúng database đích.</p></div></div><pre className="restore"><code>{current.restoreCommand}</code></pre><CopyButton value={current.restoreCommand} /><label className="admin-confirm"><input type="checkbox" checked={restoreArmed} onChange={e => setRestoreArmed(e.target.checked)} /> Tôi đã kiểm tra database đích và file backup</label><button type="button" className="admin-danger-link" disabled={!restoreArmed} onClick={() => showToast.info('Đã mở khóa hướng dẫn', 'Hãy chạy lệnh phục hồi trong operator shell, không chạy từ trình duyệt.')}>Mở khóa hướng dẫn phục hồi</button></article></section>
        <section className="admin-glass-card admin-safety-card"><div className="admin-card-heading"><span className="admin-soft-icon blue"><FileCheck2 size={18} /></span><div><h2>Checklist trước khi thao tác</h2><p>{guide?.timestamp ? `Kiểm tra lúc ${new Date(guide.timestamp).toLocaleString('vi-VN')}` : 'Các bước cần hoàn thành cho mỗi bản phát hành.'}</p></div></div><div className="admin-checklist">{(current.safety ?? []).map((item, index) => <div key={item}><span>{index + 1}</span><p>{item}</p></div>)}</div></section>
        <div className="admin-backup-footnote"><TriangleAlert size={16} /><span>Backup chỉ có giá trị khi đã kiểm tra khả năng phục hồi. Giữ ít nhất một bản ngoài máy chủ ứng dụng và ghi lại thời điểm, checksum, người thực hiện.</span></div>
    </div>;
}
