import { useState } from 'react';
import { Check, Clipboard, CreditCard, Database, Globe, Info, Shield, SlidersHorizontal } from 'lucide-react';
import '../../admin-theme.css';
import { API_URL } from '../../lib/api-config';

const paymentsEnabled = import.meta.env.VITE_PAYMENTS_ENABLED === 'true';
function CopyValue({ value }: { value: string }) { const [copied, setCopied] = useState(false); const copy = async () => { await navigator.clipboard.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1500); }; return <button className="admin-inline-copy" type="button" onClick={() => void copy()} aria-label="Sao chép giá trị">{copied ? <Check size={14} /> : <Clipboard size={14} />}</button>; }

export function SystemSettings() {
    const [showAdvanced, setShowAdvanced] = useState(false); const frontendOrigin = window.location.origin;
    const runtime = [{ title: 'Frontend origin', value: frontendOrigin, description: 'Tên miền hiện đang phục vụ bảng quản trị.', icon: Globe, tone: 'blue' }, { title: 'API backend', value: API_URL, description: 'Endpoint mà web app đang sử dụng.', icon: Database, tone: 'violet' }, { title: 'Thanh toán', value: paymentsEnabled ? 'Đang bật' : 'Đang tắt', description: paymentsEnabled ? 'Checkout đã được phép trong bản build.' : 'Đang tắt an toàn cho đến khi gateway sẵn sàng.', icon: CreditCard, tone: 'amber' }, { title: 'Quyền quản trị', value: 'Đã bảo vệ', description: 'Các route hệ thống yêu cầu phiên ADMIN hợp lệ.', icon: Shield, tone: 'green' }];
    return <div className="admin-theme admin-container p-6 md:p-8"><div className="admin-page-head"><div><p className="admin-kicker">HỆ THỐNG / CẤU HÌNH</p><h1 className="admin-title">Cấu hình hệ thống</h1><p className="admin-title-sub">Một nơi để kiểm tra runtime, release và các biến vận hành của LifeSync.</p></div><span className="admin-status-pill"><span /> Đang vận hành</span></div>
        <div className="admin-ops-banner"><div className="admin-ops-icon"><SlidersHorizontal size={21} /></div><div><strong>Cấu hình được quản lý theo môi trường</strong><p>Giá trị dưới đây được đọc từ bản build và backend. Thay đổi production nằm trong biến môi trường của hosting, sau đó redeploy để tránh chỉnh nhầm trực tiếp trên dữ liệu thật.</p></div></div>
        <section className="admin-settings-grid">{runtime.map(({ title, value, description, icon: Icon, tone }) => <article className="admin-glass-card admin-runtime-card" key={title}><div className={`admin-soft-icon ${tone}`}><Icon size={18} /></div><div className="admin-runtime-copy"><p>{title}</p><strong>{value}</strong><span>{description}</span></div><CopyValue value={value} /></article>)}</section>
        <section className="admin-settings-columns"><article className="admin-glass-card admin-settings-panel"><div className="admin-card-heading"><span className="admin-soft-icon blue"><Info size={18} /></span><div><h2>Checklist phát hành</h2><p>Kiểm tra nhanh trước khi đưa thay đổi lên production.</p></div></div><div className="admin-checklist"><div><span>1</span><p>API URL trỏ đúng backend production và phản hồi health check.</p></div><div><span>2</span><p>JWT secret, database URL và OAuth secret đã được đặt trong hosting.</p></div><div><span>3</span><p>PAYMENTS_ENABLED khớp với trạng thái gateway thực tế.</p></div><div><span>4</span><p>Chạy migration trước khi mở tính năng dùng bảng mới.</p></div></div></article><article className="admin-glass-card admin-settings-panel"><div className="admin-card-heading"><span className="admin-soft-icon green"><Shield size={18} /></span><div><h2>Phạm vi chỉnh sửa</h2><p>Phân biệt thiết lập giao diện cá nhân và vận hành hệ thống.</p></div></div><div className="admin-scope-list"><div><b>Ngay trong ứng dụng</b><span>Profile, ngôn ngữ, theme và thông báo của tài khoản.</span></div><div><b>Trong bảng quản trị</b><span>Nội dung landing page, tài khoản, log và runbook backup.</span></div><div><b>Trong hosting</b><span>Database, JWT, OAuth, payment gateway và URL triển khai.</span></div></div><button type="button" className="admin-settings-toggle" onClick={() => setShowAdvanced(v => !v)}>{showAdvanced ? 'Ẩn chi tiết kỹ thuật' : 'Hiện chi tiết kỹ thuật'}</button>{showAdvanced && <pre className="admin-env-hint"><code>VITE_WEB_API_URL{`\n`}VITE_PAYMENTS_ENABLED{`\n`}DATABASE_URL{`\n`}JWT_SECRET{`\n`}FRONTEND_URL</code></pre>}</article></section>
    </div>;
}
